### PR TITLE
Omar

### PR DESCRIPTION
**Pull request by rashadhndrxx**

### CODE REVIEW

**Review by oakj — APPROVED** [review]

**Review by chengbrian9 — CHANGES_REQUESTED** [review]
Please replace code into right container and resubmit

**Review by oakj — CHANGES_REQUESTED** [review]
- Need to move Header component and Github button component to RightContainer component

**Review by oakj — CHANGES_REQUESTED** [review]
- Dashbard.jsx has contents duplicated inside RightContainer.jsx
- Rename RightContainer component and export to be RightContainer (currently it is Dashboard)

**Review by oakj — APPROVED** [review]

**Review by rhu0 — APPROVED** [review]

**Review by chengbrian9 — APPROVED** [review]
Good stuff!

**Pull request merged**
